#ACR介绍
Remark: 镰刀ACR，日随场景经过测试，高难理论可行但是测试不足，欢迎使用并提出改进建议。2025/08/27：现在在切换地图的时候也会重置QT，如果启用了相关设置。
#支持的职业
SupportJobs:
  - 钐镰客
#支持链接
SupportUrl: https://github.com/ElliotZ/AE3-ACR
#问题反馈链接
ReportUrl: https://discord.com/channels/1191648233454313482/1403581424208183429
#是否国际服版本
EnVersion: false